[system]
# тип библиотеки на основании которой происходит обмен с сервером
#   0 - socket (по умолчанию)
#   1 - asyncio
client_type = 1

[user]
# Имя пользователя. Обязательно к определению.
login = "user"

# Пароль пользователя. Обязательно к определению.
password = "password"

[server]
# Адрес сервера
address = "http://localhost:4010/send_sms"

# Максимальное число открываемых соединений с сервером
# 0 - без ограничений (по умолчанию)
max_connections = 0

# Максимальное время ожитания ответа от сервера в мс
# 0 - без ограничений (по умолчанию)
max_time = 1000

